ReversiMvcApp/ReversiMvcApp/Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ReversiMvcApp.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ReversiMvcApp.Controllers
{
    [Authorize(Roles = "Beheerder")]
    public class RoleManagementController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleManagementController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = _userManager.Users.ToList();
            var userRolesViewModel = new List<UserRolesViewModel>();

            foreach (var user in users)
            {
                var thisViewModel = new UserRolesViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    Roles = await GetUserRoles(user)
                };
                userRolesViewModel.Add(thisViewModel);
            }

            return View(userRolesViewModel);
        }

        public async Task<IActionResult> Manage(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var model = new ManageUserRolesViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                Roles = _roleManager.Roles.ToList(),
                SelectedRoles = (await _userManager.GetRolesAsync(user)).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound();
            }

            var userRoles = await _userManager.GetRolesAsync(user);
            var selectedRoles = model.SelectedRoles ?? new List<string>();

            var result = await _userManager.AddToRolesAsync(user, selectedRoles.Except(userRoles).ToArray());

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Failed to add roles");
                return View(model);
            }

            result = await _userManager.RemoveFromRolesAsync(user, userRoles.Except(selectedRoles).ToArray());

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Failed to remove roles");
                return View(model);
            }

            return RedirectToAction("Index");
        }

        private async Task<List<string>> GetUserRoles(IdentityUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
    }
}

ReversiMvcApp/ReversiMvcApp/Controllers/SpelersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReversiMvcApp.Data;
using ReversiMvcApp.Models;
using ReversiMvcApp.Service;

namespace ReversiMvcApp.Controllers
{
    public class SpelersController : Controller
    {
        private readonly ReversiDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ReversiApi _api;

        public SpelersController(ReversiDbContext context, UserManager<IdentityUser> userManager, ReversiApi api)
        {
            _context = context;
            _userManager = userManager;
            _api = api;

        }

        // GET: Spelers
        public async Task<IActionResult> Index()
        {
              return _context.Speler != null ? 
                          View(await _context.Speler.ToListAsync()) :
                          Problem("Entity set 'ReversiDbContext.Speler'  is null.");
        }

        // GET: Spelers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            ClaimsPrincipal currentUser = this.User;
            var spelerToken = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;


            var speler = await _context.Speler
                .FirstOrDefaultAsync(m => m.GUID == spelerToken);
            if (speler == null)
            {
                return NotFound();
            }

            return View(speler);
        }

        // GET: Spelers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Spelers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GUID,Naam,AantalGewonnen,AantalVerloren,AantalGelijk")] Speler speler)
        {
            if (ModelState.IsValid)
            {
                _context.Add(speler);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(speler);
        }

        // GET: Spelers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Speler == null)
            {
                return NotFound();
            }

            var speler = await _context.Speler.FindAsync(id);
            if (speler == null)
            {
                return NotFound();
            }
            return View(speler);
        }

        // POST: Spelers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("GUID,Naam,AantalGewonnen,AantalVerloren,AantalGelijk")] Speler speler)
        {
            if (id != speler.GUID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(speler);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpelerExists(speler.GUID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(speler);
        }

        // GET: Spelers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Speler == null)
            {
                return NotFound();
            }

            var speler = await _context.Speler
                .FirstOrDefaultAsync(m => m.GUID == id);
            if (speler == null)
            {
                return NotFound();
            }

            return View(speler);
        }

        // POST: Spelers/Delete/5
        

        private bool SpelerExists(string id)
        {
          return (_context.Speler?.Any(e => e.GUID == id)).GetValueOrDefault();
        }

        [Authorize(Roles = "Beheerder, Mediator")]
        public async Task<IActionResult> List()
        {
            var spelers = await _context.Speler.ToListAsync();
            return View(spelers);
        }

        // POST: Spelers/Delete/5
        // POST: Spelers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Beheerder, Mediator")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Speler == null)
            {
                return Problem("Entity set 'ReversiDbContext.Speler' is null.");
            }

            // Find the speler
            var speler = await _context.Speler.FindAsync(id);
            if (speler == null)
            {
                return NotFound();
            }

            // Use ReversiApi to get games associated with the speler
            var games = await _api.GetAllSpellen(); // Assuming this method returns games where Speler1Token or Speler2Token matches speler.GUID

            // Delete each game associated with the speler
            foreach (var game in games)
            {
                if (game.Speler1Token == speler.GUID || game.Speler2Token == speler.GUID)
                {
                    var success = await _api.DeleteSpel(game.Token, speler.GUID);

                    if (!success)
                    {
                        // Handle failure to delete game (log, return error, etc.)
                        return Problem("Failed to delete associated game.");
                    }



                    // For now, assume the other player wins
                    var otherPlayerToken = game.Speler1Token == speler.GUID ? game.Speler2Token : game.Speler1Token;
                    var otherPlayer = await _context.Speler.FirstOrDefaultAsync(s => s.GUID == otherPlayerToken);

                    if (otherPlayer != null)
                    {
                        otherPlayer.AantalGewonnen++; // Increment wins for the other player
                    }
                }
            }

            // Remove the speler
            _context.Speler.Remove(speler);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

    }
}

ReversiMvcApp/ReversiMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReversiMvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReversiMvcApp.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("headScripts",false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReversiMvcApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spelers" asp-action="Details">Stats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spel" asp-action="Index">Game</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RoleManagement" asp-action="Index">Role Management</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-info" asp-controller="Spelers" asp-action="List">List/Delete Users</a> <!-- New link to List/Delete Users page -->
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ReversiMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>